[package]
name = "iter-fi"
version = "0.1.0"
authors = ["jt992"]
edition = "2024"
description = "Boolean composable iterators."

[dependencies]
either = { version = "1.15.0", optional = true }

[features]
default = ["branched", "std"]
branched = ["dep:either"]
std = []
